id: opecha:P006815
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG11750
  title: མཁན་ཆེན་ངག་ཆོས་ཀྱི་གསུང་ཤེར་ཕྱིན་མངོན་རྟོགས་རྒྱན་གྱི་འགྲེལ་པ་སྦས་དོན་ཟབ་མོའི་གཏེར་གྱི་ཁ་འབྱེད།
  volume: ''
  author: ''
