id: P006815
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG11750
  title: མཁན་ཆེན་ངག་ཆོས་ཀྱི་གསུང་ཤེར་ཕྱིན་མངོན་རྟོགས་རྒྱན་གྱི་འགྲེལ་པ་སྦས་དོན་ཟབ་མོའི་གཏེར་གྱི་ཁ་འབྱེད།
  author: ''
  volumes:
    288559335a304b198cd57bf33ccb4bcd:
      image_group_id: I1KG11752
      title: ''
      volume_number: 1
      total_pages: 380
